// natrium
// license : MIT
// author : Sean Chen

export enum ServerErrorCode {
    ResOK = 1,
    ResUnknown = 0,

    ResInternalError = -1,
    ResDatacompCreateError = -2,
    ResMsgParamError = -3,
    ResNotGM = -4,
    ResSysBlock = -5,

    ResAlreadyLogin = -1001,
    ResCreatePlayerError = -1002,
    ResLoinedOtherUid = -1003,
    ResLoginTokenError = -1004,
    ResServiceWrong = -1005,
    ResCreatePlayerAlreadyExist = -1006,
    ResUserLoginedByOther = -1007,
    ResUserNotExist = -1008,
    ResSessionNotLogin = -1009,
    ResServiceSessionNotExist = -1010,
    ResServicePlayerNotExist = -1011,
    ResPlayerDataNotExist = -1012,
    ResPlayerNotinMap = -1013,
    ResPlayerToMapNotExist = -1014,
    ResPlayerToSameMap = -1015,
    ResPlayerMapNoBornPos = -1016,
    ResPlayerFirstInitError = -1017,
    ResPlayerToMapPointNotExist = -1018,
    ResPlayerInSameMap = -1019,
    ResPlayerToMapPointTooFar = -1020,
    ResTargetPlayerNotExist = -1021,
    ResPlayerUnspendTxNotFindYet = -1022,
    ResPlayerUnspendTxAlreadyUsed = -1023,
    ResPlayerFeeConfError = -1024,
    ResPlayerNameAlreadyExist = -1025,
    ResPlayerPackageTypeUsed = -1026,
    ResPlayerMintFeeNotEnough = -1027,
    ResPort_MapNotExist = -2001,
    ResPort_MapMineNotExist = -2002,
    ResPort_MapMineTooFar = -2003,
    ResPort_MapMinePlyaerFull = -2005,
    ResPort_AddStoreHouseItemFailed = -2021,
    ResPort_PlayerAlreadyInMine = -2025,
    ResPort_MineOutputItemError = -2026,
    ResPlayer_NotInThisMine = -2106,
    ResPlayerRankNotExist = -2107,
}
